#!/bin/sh
#
# This script is called with the following parameters:
# interface tty speed local-address remote-address ipparam
#


# Start router advertisements on this link.
# Based on radvd 0.5.0 behaviour

DEVICE=$1

echo 1 > /proc/sys/net/ipv6/conf/$DEVICE/autoconf
echo 1 > /proc/sys/net/ipv6/conf/$DEVICE/accept_ra_pinfo
echo 2 > /proc/sys/net/ipv6/conf/$DEVICE/accept_ra
echo trigger_rs=1 > /proc/net/trigger_rs
echo wan_if=$DEVICE > /proc/net/trigger_rs
/usr/sbin/rc dhcp6c restart &

