#!/bin/sh

SYSLOG "Web Management from WAN is enabled"

case "$REMOTE_TYPE" in

	1)  # single
    if [ "$EXTERNALIP" = "NONE" -o "$EXTERNALIP" = "none" ]; then
	    $IPTABLES -t nat -I PREROUTING -i $WANIF -s $REMOTE_NET -p tcp --dport $REMOTE_PORT -j DNAT --to $INTERNALIP:80
	else
	    $IPTABLES -t nat -I PREROUTING -i $WANIF -d $EXTERNALIP -s $REMOTE_NET -p tcp --dport $REMOTE_PORT -j DNAT --to $INTERNALIP:80
	fi
	$IPTABLES -I INPUT_TCP -d $INTERNALIP -p tcp --dport 80 -j ACCEPT
	;;
	2)  # range
	if [ "$EXTERNALIP" = "NONE" -o "$EXTERNALIP" = "none" ]; then
	    $IPTABLES -t nat -I PREROUTING -i $WANIF -m iprange --src-range $REMOTE_NET -p tcp --dport $REMOTE_PORT -j DNAT --to $INTERNALIP:80
	else
	    $IPTABLES -t nat -I PREROUTING -i $WANIF -d $EXTERNALIP -m iprange --src-range $REMOTE_NET -p tcp --dport $REMOTE_PORT -j DNAT --to $INTERNALIP:80
	fi
	$IPTABLES -I INPUT_TCP -d $INTERNALIP -p tcp --dport 80 -j ACCEPT
	;;
	3)  # all
	if [ "$EXTERNALIP" = "NONE" -o "$EXTERNALIP" = "none" ]; then
	    $IPTABLES -t nat -I PREROUTING -i $WANIF  -s $REMOTE_NET -p tcp --dport $REMOTE_PORT -j DNAT --to $INTERNALIP:80
	else
	    $IPTABLES -t nat -I PREROUTING -i $WANIF -d $EXTERNALIP  -s $REMOTE_NET -p tcp --dport $REMOTE_PORT -j DNAT --to $INTERNALIP:80
	fi
	$IPTABLES -I INPUT_TCP -d $INTERNALIP -p tcp --dport 80 -j ACCEPT
	;;
esac

